services:
  www:
    build: 
      context: ./website/
      dockerfile: www.Dockerfile
    image: php:apache
    volumes:
      - "./:/var/www/html"
    environment:
      - TZ=${TIMEZONE}
      - APIKEY=${KEY}
      - MYSQL_SERVER=${SERVERNAME}
      - MYSQL_DATABASE=${DATABASE}
      - MYSQL_USER=${USER}
      - MYSQL_PASSWORD=${PASSWORD}
    ports:
      - 80:80
      - 443:443
  db:
    image: mysql:latest
    environment:
      - TZ=${TIMEZONE}
      - MYSQL_DATABASE=${DATABASE}
      - MYSQL_USER=${USER}
      - MYSQL_PASSWORD=${PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=${ALLOWEMPTYPASSWORD}
    volumes:
      - "./db/init.sql:/docker-entrypoint-initdb.d/init.sql"
      - "/opt/mysql_data:/var/lib/mysql"
  phpmyadmin:
    build:
      context: ./db/
      dockerfile: phpmyadmin.Dockerfile
    image: phpmyadmin/phpmyadmin
    volumes:
    - "./db/phpmyadmin-servername.conf:/etc/apache2/conf-available/phpmyadmin-servername.conf"
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - TZ=${TIMEZONE}
  manage_db:
    image: mysql:latest
    volumes:
      - "./db/manage_db.sh:/manage_db.sh"
      - "./db/init.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      - CLEAR_DB=${CLEAR_DB}
      - MOVE_DB=${MOVE_DB}
      - DELETE_OLD_TABLES=${DELETE_OLD_TABLES}
      - MYSQL_DATABASE=${DATABASE}
      - MYSQL_USER=${USER}
      - MYSQL_PASSWORD=${PASSWORD}
    command: ["sh", "-c", "while ! mysqladmin ping -h db --silent; do sleep 1; done; bash /manage_db.sh"]
    depends_on:
      - db
volumes:
  mysql_data:
    driver: local