services:
  www:
    build: .
    image: php:apache
    volumes:
      - "./:/var/www/html"
    environment:
      - TZ=${TIMEZONE}
      - APIKEY=${KEY}
      - MYSQL_SERVER=${SERVERNAME}
      - MYSQL_DATABASE=${DATABASE}
      - MYSQL_USER=${USER}
      - MYSQL_PASSWORD=${PASSWORD}
    ports:
      - 80:80
      - 443:443
  db:
    image: mysql:latest
    environment:
      - TZ=${TIMEZONE}
      - MYSQL_DATABASE=${DATABASE}
      - MYSQL_USER=${USER}
      - MYSQL_PASSWORD=${PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=${ALLOWEMPTYPASSWORD}
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
